from sqlalchemy import (
    CHAR,
    JSON,
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    Index,
    Integer,
    MetaData,
    String,
    Table,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.mysql import BIGINT as MySQLBigInteger

sync_records_metadata = MetaData()
record_id_type = (
    BigInteger()
    .with_variant(Integer(), "sqlite")
    .with_variant(MySQLBigInteger(unsigned=True), "mysql")
)
unsigned_bigint_type = BigInteger().with_variant(
    MySQLBigInteger(unsigned=True),
    "mysql",
)

api_config_table = Table(
    "api_config",
    sync_records_metadata,
    Column("id", record_id_type, primary_key=True, autoincrement=True),
    Column("api_code", String(100), nullable=False),
    Column("api_name", String(255), nullable=False),
    Column("enabled", Boolean, nullable=False, default=True),
    Column("platform_enabled", Boolean, nullable=False, default=False),
    Column("method", String(20), nullable=False, default="POST"),
    Column("path", String(500), nullable=False),
    Column("config_json", JSON, nullable=False),
    Column("config_version", Integer, nullable=False, default=1),
    Column("config_hash", CHAR(64), nullable=False),
    Column("read_only_verified", Boolean, nullable=False, default=False),
    Column("official_doc_id", Integer),
    Column("classification", String(64)),
    Column("execution_stage", String(64)),
    Column("published_at", DateTime, nullable=False),
    Column("remark", String(500)),
    Column("created_at", DateTime, nullable=False),
    Column("updated_at", DateTime, nullable=False),
    UniqueConstraint("api_code", name="uk_api_config_api_code"),
    Index(
        "idx_api_config_enabled",
        "enabled",
        "platform_enabled",
        "read_only_verified",
    ),
)

sync_batch_table = Table(
    "sync_batch",
    sync_records_metadata,
    Column("id", record_id_type, primary_key=True, autoincrement=True),
    Column("sync_batch_no", String(64), nullable=False),
    Column("jijia_account_id", Integer, nullable=False, default=0),
    Column("sync_job_id", Integer),
    Column("status", String(30), nullable=False),
    Column("started_at", DateTime, nullable=False),
    Column("finished_at", DateTime),
    Column("total_api_count", Integer, nullable=False, default=0),
    Column("success_api_count", Integer, nullable=False, default=0),
    Column("failed_api_count", Integer, nullable=False, default=0),
    Column("message", String(1000)),
    Column("created_at", DateTime, nullable=False),
    Column("updated_at", DateTime, nullable=False),
    UniqueConstraint("sync_batch_no", name="uk_sync_batch_no"),
    UniqueConstraint("sync_job_id", name="uk_sync_batch_job"),
    Index(
        "idx_sync_batch_account_status",
        "jijia_account_id",
        "status",
        "started_at",
    ),
)

sync_api_log_table = Table(
    "sync_api_log",
    sync_records_metadata,
    Column("id", record_id_type, primary_key=True, autoincrement=True),
    Column("sync_batch_no", String(64), nullable=False),
    Column("jijia_account_id", Integer, nullable=False, default=0),
    Column("api_code", String(100), nullable=False),
    Column("status", String(30), nullable=False),
    Column("request_count", Integer, nullable=False, default=0),
    Column("success_count", Integer, nullable=False, default=0),
    Column("failed_count", Integer, nullable=False, default=0),
    Column("started_at", DateTime, nullable=False),
    Column("finished_at", DateTime),
    Column("error_message", Text),
    Column("created_at", DateTime, nullable=False),
    Column("updated_at", DateTime, nullable=False),
    Index("idx_sync_api_log_batch", "sync_batch_no"),
    Index(
        "idx_sync_api_log_account_api_status",
        "jijia_account_id",
        "api_code",
        "status",
    ),
)

raw_api_data_table = Table(
    "raw_api_data",
    sync_records_metadata,
    Column("id", record_id_type, primary_key=True, autoincrement=True),
    Column("jijia_account_id", Integer, nullable=False, default=0),
    Column("api_code", String(100), nullable=False),
    Column("source_primary_key", String(255)),
    Column("record_identity", CHAR(64), nullable=False),
    Column("data_hash", CHAR(64), nullable=False),
    Column("raw_json", JSON, nullable=False),
    Column("data_date", Date),
    Column("sync_batch_no", String(64), nullable=False),
    Column("first_observed_at", DateTime, nullable=False, server_default=func.now()),
    Column("last_observed_at", DateTime, nullable=False, server_default=func.now()),
    Column("observation_count", unsigned_bigint_type, nullable=False, default=1),
    Column("created_at", DateTime, nullable=False),
    Column("updated_at", DateTime, nullable=False),
    UniqueConstraint(
        "jijia_account_id",
        "api_code",
        "record_identity",
        name="uk_raw_account_api_identity",
    ),
    Index(
        "idx_raw_account_api_hash",
        "jijia_account_id",
        "api_code",
        "data_hash",
    ),
    Index(
        "idx_raw_account_api_source_pk",
        "jijia_account_id",
        "api_code",
        "source_primary_key",
    ),
    Index(
        "idx_raw_api_data_date",
        "jijia_account_id",
        "api_code",
        "data_date",
    ),
    Index("idx_raw_api_batch", "sync_batch_no"),
    Index("idx_raw_created", "created_at", "id"),
    Index(
        "idx_raw_account_api_created",
        "jijia_account_id",
        "api_code",
        "created_at",
        "id",
    ),
    Index("idx_raw_last_observed", "last_observed_at"),
    Index(
        "idx_raw_account_last_observed",
        "jijia_account_id",
        "last_observed_at",
    ),
)

raw_api_data_stat_table = Table(
    "raw_api_data_stat",
    sync_records_metadata,
    Column("jijia_account_id", Integer, primary_key=True, nullable=False),
    Column("api_code", String(100), primary_key=True, nullable=False),
    Column("record_count", unsigned_bigint_type, nullable=False, server_default="0"),
    Column("created_at", DateTime, nullable=False, server_default=func.now()),
    Column("updated_at", DateTime, nullable=False, server_default=func.now()),
)

raw_api_data_history_table = Table(
    "raw_api_data_history",
    sync_records_metadata,
    Column("id", record_id_type, primary_key=True, autoincrement=True),
    Column("jijia_account_id", Integer, nullable=False, default=0),
    Column("api_code", String(100), nullable=False),
    Column("record_identity", CHAR(64), nullable=False),
    Column("source_primary_key", String(255)),
    Column("data_hash", CHAR(64), nullable=False),
    Column("raw_json", JSON, nullable=False),
    Column("data_date", Date),
    Column("sync_batch_no", String(64), nullable=False),
    Column("observed_at", DateTime, nullable=False),
    Column("created_at", DateTime, nullable=False),
    Column("updated_at", DateTime, nullable=False),
    UniqueConstraint(
        "jijia_account_id",
        "api_code",
        "record_identity",
        "data_hash",
        name="uk_raw_history_version",
    ),
    Index(
        "idx_raw_history_account_record",
        "jijia_account_id",
        "api_code",
        "record_identity",
        "observed_at",
    ),
    Index(
        "idx_raw_history_date",
        "jijia_account_id",
        "api_code",
        "data_date",
    ),
    Index("idx_raw_history_batch", "sync_batch_no"),
)

sale_return_order_table = Table(
    "sale_return_order",
    sync_records_metadata,
    Column("id", record_id_type, primary_key=True, autoincrement=True),
    Column("jijia_account_id", Integer, nullable=False),
    Column("raw_data_id", record_id_type, nullable=False),
    Column("source_primary_key", String(255), nullable=False),
    Column("record_identity", CHAR(64), nullable=False),
    Column("market_id", Integer),
    Column("return_date_time", DateTime),
    Column("order_id", String(255)),
    Column("seller_order_id", String(255)),
    Column("asin", String(32)),
    Column("msku", String(255)),
    Column("fnsku", String(255)),
    Column("sku", String(255)),
    Column("product_name", Text),
    Column("quantity", Integer),
    Column("fulfillment_center_id", String(100)),
    Column("disposition", String(100)),
    Column("reason", Text),
    Column("status", String(100)),
    Column("source_created_at", DateTime),
    Column("source_updated_at", DateTime),
    Column("data_hash", CHAR(64), nullable=False),
    Column("sync_batch_no", String(64), nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=func.now()),
    Column("updated_at", DateTime, nullable=False, server_default=func.now()),
    UniqueConstraint(
        "jijia_account_id",
        "source_primary_key",
        name="uk_sale_return_account_source",
    ),
    UniqueConstraint("raw_data_id", name="uk_sale_return_raw_data"),
    Index(
        "idx_sale_return_account_date",
        "jijia_account_id",
        "return_date_time",
        "id",
    ),
    Index(
        "idx_sale_return_account_status_date",
        "jijia_account_id",
        "status",
        "return_date_time",
    ),
    Index("idx_sale_return_account_order", "jijia_account_id", "order_id"),
    Index("idx_sale_return_account_sku", "jijia_account_id", "sku"),
    Index("idx_sale_return_created", "created_at", "id"),
)

sync_checkpoint_table = Table(
    "sync_checkpoint",
    sync_records_metadata,
    Column("id", record_id_type, primary_key=True, autoincrement=True),
    Column("jijia_account_id", Integer, nullable=False, default=0),
    Column("api_code", String(100), nullable=False),
    Column("checkpoint_kind", String(32), nullable=False),
    Column("checkpoint_value", JSON),
    Column("checkpoint_time", DateTime),
    Column("last_sync_batch_no", String(64)),
    Column("created_at", DateTime, nullable=False),
    Column("updated_at", DateTime, nullable=False),
    UniqueConstraint(
        "jijia_account_id",
        "api_code",
        "checkpoint_kind",
        name="uk_sync_checkpoint_scope",
    ),
)

failed_request_log_table = Table(
    "failed_request_log",
    sync_records_metadata,
    Column("id", record_id_type, primary_key=True, autoincrement=True),
    Column("sync_batch_no", String(64)),
    Column("jijia_account_id", Integer, nullable=False, default=0),
    Column("api_code", String(100), nullable=False),
    Column("request_url", String(1000)),
    Column("request_method", String(20), nullable=False),
    Column("request_params", JSON),
    Column("response_status_code", Integer),
    Column("response_body", Text),
    Column("error_message", Text),
    Column("retry_count", Integer, nullable=False, default=0),
    Column("created_at", DateTime, nullable=False),
    Column("updated_at", DateTime, nullable=False),
    Index(
        "idx_failed_request_account_api_created_at",
        "jijia_account_id",
        "api_code",
        "created_at",
    ),
    Index("idx_failed_request_batch", "sync_batch_no"),
)
